drive:
  inbox_folder_id: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
  archive_root_folder_id: "1K2Zitlcz7JR6Z0i77WPXAjr-2wY5hS7e"
  category_folders:
    Banca: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Salute: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Assicurazioni: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Casa: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbP"
    Auto: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Fisco: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Garanzie: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Sport: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Tecnologia: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Viaggi: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
    Varie: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"

  rules:
    - name: pdf-vecchi
      query: "mimeType='application/pdf' and modifiedTime < '2024-01-01T00:00:00' and trashed = false"
      target_folder_id: "1ty1oJt9qXTHSgibuO48Okg8Uh-esZbPr"
      remove_from_current_parents: true
      max_items: 50
